### PR TITLE
Merge plane detection and touch input to Master.

### PR DESCRIPTION
**Pull request by duc55**
# PR Summary 

This PR will add plane detection and touch input features as well as AR pose driver fix into the master branch.

Refs: #17 

## IDE Improvements 

```
Replace this section with a copy-pasta using https://github.com/youar/uberarfoundation/blob/staging/docs/InspectorResultsRider.png, then ctrl+A, then ctrl+C, and :spaghetti: Should end up look similar to the following section: 

Found issues
IssueGroupingObjectModel(groupName=Severity, text=WARNING, icon=ImageSourceIconModel (iconPackStringId = "SolutionAnalysis"iconNameStringId = "SolutionAnalysisWarning"))
IssueGroupingObjectModel(groupName=Severity, text=ERROR, icon=ImageSourceIconModel (iconPackStringId = "SolutionAnalysis"iconNameStringId = "SolutionAnalysisError"))
IssueGroupingObjectModel(groupName=Severity, text=SUGGESTION, icon=ImageSourceIconModel (iconPackStringId = "SolutionAnalysis"iconNameStringId = "SolutionAnalysisSuggestion"))
IssueGroupingObjectModel(groupName=Severity, text=HINT, icon=ImageSourceIconModel (iconPackStringId = "SolutionAnalysis"iconNameStringId = "SolutionAnalysisHint"))

Delete this auto-generated text once complete. 
```

And the image showing this improvements, in particular those for the  namespace, 

Ultimately, we have moved from  errors to  issue with internal changes in this branch.

## :ledger: Notes

No additional notes were given.

## Testing
- [ ] Build app for Android
- [ ] Build app for IOS
- [ ] Make sure `README.md` instructions to build server and client work

### Prepare Project

- Visit the project's releases page (e.g. `open https://github.com/youar/upm-xrremote/releases`)
	- [ ] Create a new release object for your git tag (i.e. `v$VERSION`).
	- [ ] Add `CHANGELOG`
- Update packages
	- [ ] `upm-xrremote.apk`

### Update Documentation
- [ ] Update `README.md` as necessary
	- [ ] Update requirements
	- [ ] Document new features

#### Build Status

- [x] Build Passes ✅ 
- [x] Build Fails :x:

### CODE REVIEW

**Comment by DiCarloJonathanBent** [comment]
@duc55 were all the packages and asm files pushed?
I get this error on a fresh clone of staging.
If so it  could potentially be an ifs push issue.
Screen Shot 2023-04-12 at 12 13 49 PM

**Comment by gblikas** [comment]
@DiCarloJonathanBent I was able to make this error go away by installing "Input System", through the Unity Package Manager, but I'm still wondering the same thing as you mentioned; the package requirement should have been pushed as a part of the PR. @duc55 thoughts? 

Screenshot 2023-04-12 at 12 41 29 PM

**Comment by duc55** [comment]
@gblikas @DiCarloJonathanBent Sorry, InputSystem is required for the touch input reader.  I didn't include it because I saw TextMeshPro package was not included.  Should I push with both of them included?  TextMeshPro is used by AR Remote Server UI.

**Comment by DiCarloJonathanBent** [comment]
@duc55 yeah might as well add the dependency for both, the main reason TMP is not already included is because it automatically asks the user to install it if it is missing.

**Comment by duc55** [comment]
@DiCarloJonathanBent Would it make sense to add dependencies for ardoundation, akcore, and arkit while I'm in there?

**Comment by duc55** [comment]
@DiCarloJonathanBent @gblikas Updated package.json with dependencies to InputSystem, TextMeshPro, ARFoundation, ARKit, and ARCore. See PR #23

**Comment by gblikas** [comment]
@duc55 do to the changes that we're doing with NDI, we're going to to close this issue and re-work later

**Pull request closed without merging**
